#include <stdio.h>

void access(){}
void chdir(){}
void chmod(){}
void chown(){}
void closedir(){}
void creat(){}
void execvp(){}
void fchmod(){}
void fchown(){}
void fopen(){}
void fork(){}
void fstat(){}
void getcwd(){}
void getgrgid(){}
void getgrnam(){}
void getpid(){}
void getpwnam(){}
void getpwuid(){}
void isatty(){}
void link(){}
void lstat(){}
void mkdir(){}
void mknod(){}
void open(){}
void opendir(){}
void putenv(){}
void readdir(){}
void readlink(){}
void rename(){}
void rmdir(){}
void stat(){}
void symlink(){}
void sync(){}
void umask(){}
void unlink(){}
void utime(){}
void waitpid(){}
